language: php

sudo: false

php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - master

before_script:
    - composer self-update
    - composer install --no-interaction --prefer-source --dev

script:
    - vendor/bin/phpunit --configuration phpunit.xml
